### ISSUE TITLE
Group sort?

### ISSUE THREAD

**Issue by typemytype** [BelaFrank/RoboFont-scripts#1]
RoboFont does not sort groups, that is totally up to the user.. 

If Im wrong can you provide an example of a wrongly sorted group?

Thanks

**Comment by FrankFonts** [comment]
No, I've just realised I was wrong, it wasn't RoboFont. I set up a group in MetricsMachine, like 
_@MMK_L_e = e egrave eacute ... ecaron ae aeacute_
saved it, opened it up in TextMate and found the glyphs in the group sorted alphabetically
_@MMK_L_e = ae aeacute e eacute ebreve ecaron ... emacron eogonek_

But then again, it wasn't RoboFont. I removed the part in question from the ReadMe. 
Thanks Frederik!
